export const access = {
  metaTitle: "Acceso · Biofonía",
  aside: {
    eyebrow: "Entre laboratorio y territorio",
    title: "Entra en la conversación.",
    lead: "Con una cuenta puedes:",
    benefits: [
      { text: "Publicar y comentar sin esperar revisión", tone: "pink" },
      { text: "Votar por las publicaciones que te interesan", tone: "pink" },
      { text: "Guardar borradores y ver tu historial", tone: "olive" },
      { text: "Personalizar tu perfil y tus temas", tone: "olive" },
    ],
    soundwaveLabel: "Onda de sonido de laboratorio y territorio",
    readOnly: "¿Solo quieres leer? No necesitas cuenta.",
    explore: "Explorar sin cuenta",
  },
  tabsLabel: "Acceso a Biofonía",
  divider: "o con tu correo",
  googleError:
    "No pudimos iniciar sesión con Google. Inténtalo de nuevo o usa tu correo.",
  login: {
    tab: "Iniciar sesión",
    title: "Qué bueno verte de nuevo",
    lead: "Inicia sesión para publicar, votar y seguir tus conversaciones.",
    google: "Continuar con Google",
    email: "Correo electrónico",
    password: "Contraseña",
    forgot: "¿Olvidaste tu contraseña?",
    forgotSoon: "Próximamente",
    submit: "Iniciar sesión",
    switchPrompt: "¿Aún no tienes cuenta?",
    switchAction: "Crea una",
  },
  register: {
    tab: "Crear cuenta",
    title: "Crea tu cuenta",
    lead: "Comparte lo que ves y pregunta lo que te intriga, desde el laboratorio o desde el territorio.",
    google: "Registrarse con Google",
    name: "Nombre completo",
    email: "Correo electrónico",
    password: "Contraseña",
    passwordHint: "Al menos 8 caracteres.",
    rulesPrefix: "Acepto las",
    rulesLink: "normas del foro",
    submit: "Crear cuenta",
    switchPrompt: "¿Ya tienes cuenta?",
    switchAction: "Inicia sesión",
  },
  emailPlaceholder: "nombre@correo.com",
} as const;

export const onboarding = {
  metaTitle: "Bienvenida · Biofonía",
  stepLabel: (step: number, total: number) => `Paso ${step} de ${total}`,
  next: "Continuar",
  back: "Atrás",
  finish: "Terminar",
  role: {
    eyebrow: "Tu cuenta está lista",
    title: "¿Desde dónde llegas a la conversación?",
    lead: "Esto ayuda a otras personas a entender tu mirada. Ninguna vale más que la otra.",
    legend: "Tu perfil",
    options: [
      {
        value: "IN_LABORATORY",
        kicker: "Desde el laboratorio",
        title: "Científico o científica",
        text: "Investigas en la academia o en un centro de investigación.",
        tone: "olive",
        icon: "M9 3h6M10 3v6l-5 9a2 2 0 0 0 1.7 3h10.6a2 2 0 0 0 1.7-3l-5-9V3M7.5 15h9",
        bioPlaceholder:
          "Ej.: Investigo materiales inspirados en la naturaleza en el CICIMA. Me interesa aprender de quienes trabajan en el campo.",
      },
      {
        value: "IN_FIELD",
        kicker: "Desde el territorio",
        title: "Persona en el campo",
        text: "Conoces la naturaleza por observarla, trabajarla o habitarla.",
        tone: "pink",
        icon: "M12 21V11M12 11c0-4 3-7 7-7 0 4-3 7-7 7zM12 14c0-3-2.5-5.5-6-5.5 0 3.5 2.5 5.5 6 5.5zM5 21h14",
        bioPlaceholder:
          "Ej.: Guía naturalista en Osa. Llevo veinte años observando aves y anfibios en el bosque.",
      },
    ],
  },
  bio: {
    eyebrow: "Biografía",
    title: "Cuéntanos quién eres",
    lead: "Un resumen breve: qué haces, dónde estás y qué te interesa observar o investigar.",
    label: "Tu biografía",
    help: "Podrás editarla después desde tu perfil.",
    maxLength: 280,
  },
} as const;
