export const profile = {
  metaTitle: "Mi perfil · Biofonía",
  metaTitleOf: (name: string) => `${name} · Biofonía`,
  avatarLabel: (name: string) => `Foto de perfil de ${name}`,
  memberSince: (monthYear: string) => `En Biofonía desde ${monthYear}`,
  editProfile: "Editar perfil",
  edit: {
    metaTitle: "Editar perfil · Biofonía",
    href: "/perfil/editar",
    back: "Volver a mi perfil",
    title: "Editar perfil",
    lead: "Así te ven las demás personas del foro. Puedes cambiarlo cuando quieras.",
    name: { label: "Nombre" },
    role: { legend: "¿Desde dónde llegas a la conversación?" },
    bio: {
      label: "Tu biografía",
      help: "Qué haces, dónde estás y qué te interesa observar o investigar.",
    },
    save: "Guardar cambios",
    cancel: "Cancelar",
  },
  stats: {
    published: "Publicaciones",
    votes: "Votos recibidos",
  },
  posts: {
    ownTitle: "Mis publicaciones",
    title: "Publicaciones",
    viewsLabel: "Vista de publicaciones",
    views: { published: "Publicadas", drafts: "Borradores" },
    searchLabel: "Buscar en las publicaciones",
    searchPlaceholder: "Buscar en las publicaciones",
    categoriesLabel: "Filtrar por categoría",
    allCategories: "Todas",
    uncategorized: "Sin categoría",
    draft: "Borrador · Sin publicar",
    empty: "No hay publicaciones que coincidan con este filtro.",
    noPosts: "Todavía no hay publicaciones.",
  },
} as const;
